<template>
  <div>
  <b-carousel
    id="carousel-fade"
    style="text-shadow: 0px 0px 2px #000"
    fade
    indicators
    img-width="1024"
    img-height="480"
  >
    <b-carousel-slide
      caption=""
      img-src="https://wallpapercave.com/wp/wp5498323.png"
    ></b-carousel-slide>
    <b-carousel-slide
      caption=""
      img-src="https://nhrwallpapers.com/wp-content/uploads/2021/04/Aesthetic-Wallpaper-For-Desktop.jpg"
    ></b-carousel-slide>
    <b-carousel-slide
      caption=""
      img-src="https://wallpapercave.com/wp/wp5440358.jpg"
    ></b-carousel-slide>
  </b-carousel>
</div>
</template>